storage:
  tsdb:
    # A 10min time window is enough because it can easily absorb retries and network delays.
    out_of_order_time_window: 10m
remote_write:
#   - url: "http://localhost:9090/api/v1/write"